### ISSUE TITLE
Parachute click is off

### ISSUE THREAD

**Issue by k4deng** [filadog/TinyClicker#5]
When using TinyClicker, the parachute clicking mechanism is irregular and sometimes does not click the parachute correctly.

https://user-images.githubusercontent.com/70725766/203849363-cfc80e58-ee4c-4484-adc6-94fcb7d687bf.mp4

As you can see in the video, the tap (little grey dot) is always in the top right of the parachute and fails to tap it correctly.

This becomes a major problem when the parachute is above the build floor button and the clicker taps on the build floor button and freezes up.

**Comment by filadog** [comment]
Attempted to fix the issue in the [latest release](https://github.com/filadog/TinyClicker/releases/tag/v1.3), should work now correctly
