### ISSUE TITLE
TinyClicker won't click the "awesome" button 

### ISSUE THREAD

**Issue by joshuatly** [filadog/TinyClicker#8]
Thanks for creating and maintaining the project. 

When there are events running, delivering bits will result in a prompt which gives pumpkin or bells
The button to close that is not "continue" but "awesome" which I think the latest version still does not handle.

I'm wondering if there are ways I can make it work, eg changing language etc. 
![Screenshot_20231201-003824.png](https://github.com/filadog/TinyClicker/assets/8279975/45ccdad8-2fde-4774-86d5-d027cb1baa08)

**Comment by filadog** [comment]
Hey @joshuatly, thank you for the feedback! I couldn't find a window with this button in the game, perhaps it was visible during some recent event? Despite that, I found some screenshots online and managed to add functionality to click on this button in the last version (v1.13), please let me know if it works now. [Latest release is available here.](https://github.com/filadog/TinyClicker/releases/tag/v1.13)

**Comment by joshuatly** [comment]
Yeah, this is visible only during events. 
Happy to report it works now! Thanks!
You're awesome.
