### ISSUE TITLE
Issue with version 1.14 and above, and requesting new build for new version

### ISSUE THREAD

**Issue by joshuatly** [filadog/TinyClicker#9]
Hi filadog thanks a lot for writing this. I'm currently having issue using TinyClicker 1.14 and above, I just cannot get it to work smoothly with BlueStack 5. It will usually get stuck at some screen (build a new floor at cost of x coins). 

Before the latest event update, I was able to use v.1.13.

A few notes with the program, I usually have to adjust the bluestack window size to get it to work well. 
I noticed when it get bigger, sometimes it will not collect the 20 bucks every 5 minutes, and will click on the build new floor, which will get stucked

Collecting science points doesnt seems to work on my setup (v.1.13) as well. 

Let me know if there are anything I can help with improving this. 

Oh and also, if we can get a new build that will work for the new version of TinyClicker, that will be super awesome.

**Comment by filadog** [comment]
Hey @joshuatly, I've fixed some issues related to the changes in user interface of the game. Please check out the [latest release here](https://github.com/filadog/TinyClicker/releases/tag/v1.15) and let me know if some issues are not fixed. Thanks.

**Comment by joshuatly** [comment]
Hi, i was trying the latest version and so happen to be able to record one of the problem i face:
[Video to screen recording](https://pixeldrain.com/u/FPAdkrxE)

I checked the folder, there is no log that i can upload for you right now. 

Before the UI update, I was able to use edit the source code of 1.13 and build with the new button coordinate, and it worked relatively well (compare to 1.14)

Again, really appreciate you keeping this maintained. Cheers!

**Comment by filadog** [comment]
@joshuatly thanks for the video, the problem should be fixed now [in the last release (v1.16)](https://github.com/filadog/TinyClicker/releases/tag/v1.16)

**Comment by joshuatly** [comment]
Thanks for the quick fix. Ive downloaded it and will let it run for a bit. But so far so good!

**Comment by joshuatly** [comment]
One more bug if you dont mind, the claiming of tech/science point is stucked here:
[Screenshot](https://pixeldrain.com/api/file/gr5riK6g)

**Comment by filadog** [comment]
Closing the issue cause the project will not receive any updates in the future.
